name: googletry
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  google_sign_in: ^6.2.1
  the_apple_sign_in: ^1.1.1
  cloud_firestore: ^4.15.0
  flutterfire_cli: ^0.3.0-dev.20
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  assets:
    - ./assets/images/
    - ./assets/launcher_icons/dev.png
    - ./assets/launcher_icons/prd.png
    - ./assets/launcher_icons/stg.png
